version: '3'
services:
  app:
    build:
      context: .
    command: task run
    ports:
      - "8000:8000" # Change to the port your app runs on
    depends_on:
      - redis
      - postgres
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: postgres://postgres_user:password@postgres/melipolibre
      REDIS_URL: redis://redis:6379/0
    networks:
      - melipolibre_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: melipolibre
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - melipolibre_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - melipolibre_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - melipolibre_network

networks:
  melipolibre_network:
    driver: bridge

volumes:
  postgres_data:
